snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: oiysujp-vx60923
      # User/password auth
      user: Rao
      password: Mads1265*
      role: ACCOUNTADMIN
      database: DBT_DEMO
      warehouse: COMPUTE_WH
      schema: DBTCORE
      threads: 10
      client_session_keep_alive: False
      query_tag: demo

      # optional
      #connect_retries: 0 # default 0
      #connect_timeout: 10 # default: 10
      #retry_on_database_errors: False # default: false

      #retry_all: False  # default: false
      #reuse_connections: False # default: false (available v1.4+)
  target: dev
